vcap:
  application:
    name: '@project.name@'
spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: "off"
  cloud:
    bus:
      enabled: false
    config:
      enabled: false
eureka:
  client:
    enabled: false
info:
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    
---
spring:
  profiles: qq
rabbit-load-generator:
  rabbitServiceName: rabbitmq-04
  scenarios:
  # Creates 33 connections, 330 channels, 990 quorum queues, 990 bindings, and 19800 consumers
  # For each of the 999 bindings, a message is published every 120 seconds for a total throughput of 8.3 msgs/sec
  # Start 4 instances of this profile to match CareAware's NONPROD-01 cluster
  - queueNamePrefix: quorum-
    uniqueExchange: true
    connections: 33
    channelsPerConnection: 10
    queuesPerChannel: 3
    consumersPerQueue: 20
    bindingsPerQueue: 1
    autoDelete: false
    durable: true
    quorum: true
    publishInterval: 120000
    publishPersistent: true
    publishMsgSizeBytes: 20000

---
spring:
  profiles: durable-mirrored
rabbit-load-generator:
  rabbitServiceName: rabbitmq-04
  scenarios:
  # Creates 33 connections, 330 channels, 990 durable classic queues, 990 bindings, and 9900 consumers
  # For each of the 999 bindings, a request/reply is performed every 60 seconds for a total throughput of 16.5 requests/sec
  # Start 7 instances of this profile to match CareAware's NONPROD-01 cluster
  - queueNamePrefix: classic-durable-mirrored-
    uniqueExchange: true
    connections: 33
    channelsPerConnection: 10
    queuesPerChannel: 3
    consumersPerQueue: 10
    bindingsPerQueue: 1
    autoDelete: false
    durable: true
    quorum: false
    publishInterval: 0
    requestInterval: 60000
    requestMsgSizeBytes: 10000
    replyMsgSizeBytes: 500000

---
spring:
  profiles: autodelete
rabbit-load-generator:
  rabbitServiceName: rabbitmq-04
  scenarios:
  # Creates 33 connections, 330 channels, 990 transient classic queues, 1980 bindings, and 990 consumers
  # For each of the 1998 bindings, a message is published every 240 seconds for a total throughput of 8.3 msgs/sec
  # Start 7 instances of this profile to match CareAware's NONPROD-01 cluster
  - queueNamePrefix: classic-autodelete-
    uniqueExchange: true
    connections: 33
    channelsPerConnection: 10
    queuesPerChannel: 3
    consumersPerQueue: 1
    bindingsPerQueue: 2
    autoDelete: true
    durable: false
    quorum: false
    publishInterval: 240000
    publishPersistent: false
    publishMsgSizeBytes: 20000