vcap:
  application:
    name: '@project.name@'
spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: "off"
  cloud:
    bus:
      enabled: false
    config:
      enabled: false
eureka:
  client:
    enabled: false
info:
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    
---
spring:
  profiles: 1k-qq
rabbit-load-generator:
  rabbitServiceName: rabbitmq-04
  scenarios:
  # Creates 33 connections, 330 channels, 999 quorum queues, 999 bindings, and 15984 consumers
  # For each of the 999 bindings, a message is published every 120 seconds for a total throughput of 8.3 msgs/sec
  # Start 4 instances of this profile to match CareAware's NONPROD-01 cluster
  - queueNamePrefix: quorum-
    connections: 33
    channelsPerConnection: 10
    queuesPerChannel: 3
    consumersPerQueue: 16
    bindingsPerQueue: 1
    autoDelete: false
    isDurable: true
    isQuorum: true
    publishInterval: 120000
    publishPersistent: true

---
spring:
  profiles: 1k-durable-mirrored
rabbit-load-generator:
  rabbitServiceName: rabbitmq-04
  scenarios:
  # Creates 33 connections, 330 channels, 999 durable classic queues, 999 bindings, and 7992 consumers
  # For each of the 999 bindings, a message is published every 120 seconds for a total throughput of 8.3 msgs/sec
  # Start 7 instances of this profile to match CareAware's NONPROD-01 cluster
  - queueNamePrefix: classic-durable-mirrored-
    connections: 33
    channelsPerConnection: 10
    queuesPerChannel: 3
    consumersPerQueue: 8
    bindingsPerQueue: 1
    autoDelete: false
    isDurable: true
    isQuorum: false
    publishInterval: 120000
    publishPersistent: true

---
spring:
  profiles: 1k-autodelete
rabbit-load-generator:
  rabbitServiceName: rabbitmq-04
  scenarios:
  # Creates 33 connections, 330 channels, 999 transient classic queues, 1998 bindings, and 999 consumers
  # For each of the 1998 bindings, a message is published every 180 seconds for a total throughput of 11.1 msgs/sec
  # Start 7 instances of this profile to match CareAware's NONPROD-01 cluster
  - queueNamePrefix: classic-autodelete-
    connections: 33
    channelsPerConnection: 10
    queuesPerChannel: 3
    consumersPerQueue: 1
    bindingsPerQueue: 2
    autoDelete: true
    isDurable: false
    isQuorum: false
    publishInterval: 180000
    publishPersistent: false